name: 'Microsoft Teams Notifications DC'
description: 'Send a custom notification message to a Microsoft Teams channel with GitHub repo details'
author: 'dragos-cojocari'
branding:
  icon: message-circle
  color: purple 
inputs:
  github-token:
    description: 'GitHub Token'
    required: true 
  ms-teams-webhook-uri:
    description: 'Microsoft Teams Webhook URI'
    required: true 
  notification-summary:
    description: 'Message to be sent to Microsoft Teams channel'
    required: true 
  notification-color:
    description: 'Color of notification header line'
    required: true 
  timezone:
    description: 'Timezone (ex. America/Denver)'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
