name: "Build & Test"
on: # rebuild any PRs and main branch changes
  repository_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        npm install
        npm run all
    - name: Test
      uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Deployment Started 
        notification-color: 17a2b8
        timezone: America/Denver 
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Warning! Something Not Quite Right 
        notification-color: ffc107
        timezone: America/Denver 
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: OMG!! Something Exploded
        notification-color: dc3545
        timezone: America/Denver 
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Whew! Everything is right with the world again! 
        notification-color: 28a745 
        timezone: America/Denver 
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: "Emojify! &#x1F6A2​​ &#x2705;"
        notification-color: 28a745 
        timezone: America/Denver 
