name: "Build & Test"
on: # rebuild any PRs and main branch changes
  repository_dispatch:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.DATA_SQUAD_DEPLOYMENT_FAILURE_TEAMS_WEBHOOK_URI }}
          notification-summary: Testing changes to https://github.com/cinch-labs/ms-teams-notification
          notification-color: 17a2b8
          timezone: Europe/London
      - uses: ./
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: TEST! Warning! Something Not Quite Right
          notification-color: ffc107
          timezone: America/Denver
      - uses: ./
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: TEST! OMG!! Something Exploded
          notification-color: dc3545
          timezone: America/Denver
      - uses: ./
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: TEST! Whew! Everything is right with the world again!
          notification-color: 28a745
          timezone: America/Denver
      - uses: ./
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Emojify! &#x1F6A2​​ &#x2705;"
          notification-color: 28a745
          timezone: America/Denver
